version: '3'
services:
  www:
    env_file:
      - /opt/app/.env

    volumes:
      - .:/opt/app/
    ports:
      - '80:80'
    build:
      context: .

  redis:
    image: redis:5-alpine
    container_name: cache
    volumes:
      - /opt/app/db/:/data/db
    expose:
      - 6379

